### ISSUE TITLE
tree-sitter-cli compatibility

### ISSUE THREAD

**Issue by char0n** [Menci/tree-sitter-wasm-prebuilt#2]
Hi @Menci,

This repo is currently using [tree-sitter-cli@0.16.5](https://www.npmjs.com/package/tree-sitter-cli/v/0.16.5). The moment `tree-siter-cli` is updated to `>=0.16.6` the WASM compile successfully but when you try to run it in browser you'll get:

```
Couldn't find language function in WASM file. Symbols:
[
  "__post_instantiate",
  "dynCall_X",
  "dynCall_i",
  "dynCall_iii",
  "dynCall_iiii",
  "dynCall_vi",
  "dynCall_vii",
  "dynCall_viii"
]
```
I've already reported this to YAML grammar author (https://github.com/ikatyang/tree-sitter-yaml/issues/6).

**Comment by Menci** [comment]
I will update the dependencies.
